<a href="https://colab.research.google.com/github/ruthgrubio/matem-ticas/blob/main/PRACTICA%20ALGEBRA%20RUTH%20GARC%C3%8DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [ ]:
from random import randint, choice

N = 3
M = 3

m = [[randint(1,9) * choice ([1, -1]) for j in range(M)] for i in range(N)]


for f in m:
    print(f)
    

     

[5, 3, 5]
[-4, -2, -6]
[-9, 6, -4]


In [ ]:
import numpy as np

n = 3   # orden nxn de la matriz cuadrada

while True:
    m = np.random.randint(-9,10, size=(n, n))   # aleatorios enteros entre -9 y +9
    determ = np.linalg.det(m)
    if determ == 1:
        print(m)
        break

print(f"El determinante de la matriz es {determ}")
     

[[ 1  2  4]
 [-2 -3  6]
 [ 1  1 -9]]
El determinante de la matriz es 1.0


In [ ]:
import numpy as np
m = np.array([[1,2,4],[-2,-3,6],[1,1,-9]])
print("Matriz:")
print(m)
print("\nTranspuesta:")
print(np.transpose(m))

Matriz:
[[ 1  2  4]
 [-2 -3  6]
 [ 1  1 -9]]

Transpuesta:
[[ 1 -2  1]
 [ 2 -3  1]
 [ 4  6 -9]]


In [ ]:
print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()

Inversa:
[[ 21.  22.  24.]
 [-12. -13. -14.]
 [  1.   1.   1.]]



In [ ]:
print("Matriz Identidad:")
identidad = np.dot(m, minv)   # multiplicación de matrices
print(identidad)
print()

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
print("Matriz Identidad con valores enteros:")
print(identidad.astype(int))  
     

Matriz Identidad con valores enteros:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
from time import process_time

t1 = process_time()

for i in range(10_000_000):
    cuadrado = i**2

t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")

El proceso ha tardado 3.269525182999999 segundos.


## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

In [ ]:
list(range(-5,0)) + list(range(1,5))

[-5, -4, -3, -2, -1, 1, 2, 3, 4]

In [1]:
import numpy as np
v = np.array([3,4,5,2])   # solución del sistema lineal

def busca(b):
    while True:
        w = np.random.choice(list(range(-5,0)) + list(range(1,6)), 4)
        if np.matmul(v, w) == b:   # el producto de los vectores debe ser igual al nº b
            break
    return w

f1 = np.array([1,3,-1,-2])   # la primera fila de la matriz A nos la dan como dato
f2 = busca(3)                # las demás filas se general aleatoriamente
f3 = busca(5)                # cumpliendo la condición de que Ax=b
f4 = busca(7)

B = np.array([6,3,5,7])      # vector B con los términos independientes
print(f"{f1} x {v} = {6}")
print(f"{f2} x {v} = {3}")
print(f"{f3} x {v} = {5}")
print(f"{f4} x {v} = {7}")
print()

A = np.array([f1,f2,f3,f4])  # matriz A de coeficientes del sistema lineal

print(f"La matriz A es: \n{A}")
print()

print("Comprobación de que se obtiene la solución del sistema:")
print("Método 1: usando la matriz inversa")
print(np.linalg.inv(A) @ B)
print("Método 2: usando Solve")
print(np.linalg.solve(A,B))

[ 1  3 -1 -2] x [3 4 5 2] = 6
[ 2  4 -3 -2] x [3 4 5 2] = 3
[ 4 -3 -1  5] x [3 4 5 2] = 5
[-4  2  1  3] x [3 4 5 2] = 7

La matriz A es: 
[[ 1  3 -1 -2]
 [ 2  4 -3 -2]
 [ 4 -3 -1  5]
 [-4  2  1  3]]

Comprobación de que se obtiene la solución del sistema:
Método 1: usando la matriz inversa
[3. 4. 5. 2.]
Método 2: usando Solve
[3. 4. 5. 2.]


In [6]:
determ = np.linalg.det(A)
print(f"El determinante de esta matriz es {determ}")


El determinante de esta matriz es -149.00000000000014


In [7]:
print("Inversa:")
minv = np.linalg.inv(A)
print(minv)
print()

Inversa:
[[ 0.58389262 -0.27516779  0.16778523 -0.0738255 ]
 [ 0.53691275 -0.16107383  0.0738255   0.12751678]
 [ 1.06040268 -0.71812081  0.12080537  0.02684564]
 [ 0.06711409 -0.02013423  0.13422819  0.1409396 ]]



In [ ]:
import numpy as np
a = np.array([[1,3,-1,-2], [3,3,-2,-4], [3,-4,2,1], [-2,4,-1,1]])
b = np.array([3,4,5,2])
a_inv = np.linalg.inv(a)
np.dot(a_inv, b)
     

array([2.66666667, 1.55555556, 0.7037037 , 1.81481481])

In [ ]:
import numpy as np
a = np.array([[1,3,-1,-2], [3,3,-2,-4], [3,-4,2,1], [-2,4,-1,1]])
b = np.array([3,4,5,2])
solucion = np.linalg.solve(a,b)
solucion

array([2.66666667, 1.55555556, 0.7037037 , 1.81481481])

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

## Escribir con $\LaTeX$
Tenemos que escribir un sistema lineal de 4 ecuaciones con 4 incognitas 
$$\left.
\begin{align*}
+x + 3y -z  -2t &= 6 \\
2x + 4y -3z -2t &= 3 \\
4x - 3y -z  +5t &= 5 \\
-4x+ 2y +z  +3t &= 7 
\end{align*}
\right\}$$


In [ ]:
!apt install octave


In [ ]:
!apt update

In [11]:
%%writefile pru.m
x = 2
y = 3
display(x+y)

Writing pru.m


In [21]:
!octave pru.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
x =  2
y =  3
 5


In [15]:
%%writefile primero.m
A = [1 +3 -1 -2; 2 +4 -3 -2; 4 -3 -1 +5; -4 +2 +1 +3]
b = [+6; +3; +5; +7]
x= inv(A)*b
% solución 1, rats expresa los número como fracciones o enteros
s1 =rats(x)

Writing primero.m


In [16]:
!octave primero.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
A =

   1   3  -1  -2
   2   4  -3  -2
   4  -3  -1   5
  -4   2   1   3

b =

   6
   3
   5
   7

x =

   3.0000
   4.0000
   5.0000
   2.0000

s1 =

          3
          4
          5
          2



In [19]:
%%writefile segundo.m
G = [1 +3 -1 -2 +6; 2 +4 -3 -2 +3; 4 -3 -1 5 +5; -4 2 1 3 +7]
escalonada = rref(G)
% solución 2
s2 = rats(escalonada)

Overwriting segundo.m


In [20]:
!octave segundo.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
G =

   1   3  -1  -2   6
   2   4  -3  -2   3
   4  -3  -1   5   5
  -4   2   1   3   7

escalonada =

   1.00000   0.00000   0.00000   0.00000   3.00000
   0.00000   1.00000   0.00000   0.00000   4.00000
   0.00000   0.00000   1.00000   0.00000   5.00000
   0.00000   0.00000   0.00000   1.00000   2.00000

s2 =

          1          0          0          0          3
          0          1          0          0          4
          0          0          1          0          5
          0          0          0          1          2



Después de realizar ambos dos métodos podremos observar como da lo mismo. 

## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

In [ ]:
#AUTOVALORES Y AUTOVECTORES
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

X = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
print(X)

print(np.linalg.eig(X))

[[-1 -2  3 -1]
 [ 0  2  0  0]
 [ 0  0  2  0]
 [ 0  0  0  1]]
(array([-1.,  2.,  2.,  1.]), array([[ 1.        , -0.5547002 ,  0.70710678, -0.4472136 ],
       [ 0.        ,  0.83205029,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.89442719]]))


In [ ]:
# Nos devuelve un vector con los autovalores y una matriz con los autovectores
autovalores, autovectores = np.linalg.eig(X)
print(autovalores)
print(autovectores)

[-1.  2.  2.  1.]
[[ 1.         -0.5547002   0.70710678 -0.4472136 ]
 [ 0.          0.83205029  0.          0.        ]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.          0.          0.          0.89442719]]


In [ ]:
#MATRIZ DIAGONAL
from sympy import Matrix
A = Matrix([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
P, D = A.diagonalize()
D   

Matrix([
[-1, 0, 0, 0],
[ 0, 1, 0, 0],
[ 0, 0, 2, 0],
[ 0, 0, 0, 2]])

In [ ]:
#MATRIZ DE PASO
P


Matrix([
[1, -1, -2, 1],
[0,  0,  3, 0],
[0,  0,  0, 1],
[0,  2,  0, 0]])

In [ ]:
m = np.array([[1,-1,-2,1], [0,0,3,0], [0,0,0,1], [0,2,0,0]])
print("Matriz:")
print(m)
print()

print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()


Matriz:
[[ 1 -1 -2  1]
 [ 0  0  3  0]
 [ 0  0  0  1]
 [ 0  2  0  0]]

Inversa:
[[ 1.          0.66666667 -1.          0.5       ]
 [ 0.          0.          0.          0.5       ]
 [ 0.          0.33333333  0.          0.        ]
 [ 0.          0.          1.          0.        ]]



In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))
     

d:  [-1.  2.  2.  1.]

D:
 [[-1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  1.]]

P:
 [[ 1.         -0.5547002   0.70710678 -0.4472136 ]
 [ 0.          0.83205029  0.          0.        ]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.          0.          0.          0.89442719]]

Dcubo:
 [[-1.  0.  0.  0.]
 [ 0.  8.  0.  0.]
 [ 0.  0.  8.  0.]
 [ 0.  0.  0.  1.]]

Solución:
 [[-1. -6.  9. -1.]
 [ 0.  8.  0.  0.]
 [ 0.  0.  8.  0.]
 [ 0.  0.  0.  1.]]


In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
print(A@A@A)
     

[[-1 -6  9 -1]
 [ 0  8  0  0]
 [ 0  0  8  0]
 [ 0  0  0  1]]


## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

In [ ]:
!apt install octave
!apt update

Reading package lists... Done
Building dependency tree       
Reading state information... Done
octave is already the newest version (4.2.2-1ubuntu1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:10 htt

In [ ]:
%%writefile diagonaliza.m
A = [-1,-2,3,-1; 0,2,0,0; 0,0,2,0; 0,0,0,1]
[P,D]=eig(A)
Dcubo = D^3
Acubo = A^3
PxDcuboXPinv = P*Dcubo*P^-1

Overwriting diagonaliza.m


In [ ]:
!octave diagonaliza.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
A =

  -1  -2   3  -1
   0   2   0   0
   0   0   2   0
   0   0   0   1

P =

   1.00000  -0.55470   0.70711  -0.44721
   0.00000   0.83205   0.00000   0.00000
   0.00000   0.00000   0.70711   0.00000
   0.00000   0.00000   0.00000   0.89443

D =

Diagonal Matrix

  -1   0   0   0
   0   2   0   0
   0   0   2   0
   0   0   0   1

Dcubo =

Diagonal Matrix

  -1   0   0   0
   0   8   0   0
   0   0   8   0
   0   0   0   1

Acubo =

  -1  -6   9  -1
   0   8   0   0
   0   0   8   0
   0   0   0   1

PxDcuboXPinv =

  -1  -6   9  -1
   0   8   0   0
   0   0   8   0
   0   0   0   1



## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

In [ ]:
!apt install octave
!apt update

Reading package lists... Done
Building dependency tree       
Reading state information... Done
octave is already the newest version (4.2.2-1ubuntu1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:10 http://

In [ ]:
%%writefile proceso.m
empleados = 1000
% state vector
inicial = [.9; .1]
% transition probability matrix
A = [.6, .3; .4, .7]
[P,D]=eig(A)
Dcuadrado = D^2
Acuadrado = A^2
PxDcuadradoXPinv = P*Dcuadrado*P^-1
dia2 = Acuadrado * inicial
disp("Nº de empleados que se quedan en casa el segundo día: "), disp(dia2(2)*empleados)
D10 = D^10
A10 = P*D10*P^-1
dia10 = A10 * inicial
disp("Nº de empleados que se quedan en casa a largo plazo son: "), disp(dia10(2)*empleados)
     

Overwriting proceso.m


In [ ]:
!octave proceso.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
empleados =  1000
inicial =

   0.90000
   0.10000

A =

   0.60000   0.30000
   0.40000   0.70000

P =

  -0.70711  -0.60000
   0.70711  -0.80000

D =

Diagonal Matrix

   0.30000         0
         0   1.00000

Dcuadrado =

Diagonal Matrix

   0.090000          0
          0   1.000000

Acuadrado =

   0.48000   0.39000
   0.52000   0.61000

PxDcuadradoXPinv =

   0.48000   0.39000
   0.52000   0.61000

dia2 =

   0.47100
   0.52900

Nº de empleados que se quedan en casa el segundo día: 
 529
D10 =

Diagonal Matrix

   5.9049e-06            0
            0   1.0000e+00

A10 =

   0.42857   0.42857
   0.57143   0.57143

dia10 =

   0.42857
   0.57143

Nº de empleados que se quedan en casa a largo plazo son: 
 571.43


## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

In [ ]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)
A10 = P@(D**10)@Pinv
X10 = A10@X0
print("Situación a los diez años:", X10)
print("Situación a los veinte años:", P@(D**20)@Pinv@X0)

Situación a los tres años: [0.672 0.328]
Situación a los diez años: [0.6666754 0.3333246]
Situación a los veinte años: [0.66666667 0.33333333]
